my_site/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path("cart_add", views.cart_add, name="cart_add"),
    path("cart_change", views.cart_change, name="cart_change"),
    path("cart_remove", views.cart_remove, name="cart_remove"),
]

my_site/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
]

my_site/my_site/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="order")),
]

if settings.DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path("create-order", views.create_order, name="create_order"),
]

my_site/carts/models.py
from django.db import models
from users.models import User

from goods.models import Product


# Create your models here.

class CartQuerySet(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Пользователь', blank=True, null=True)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=32, blank=True, null=True, verbose_name='Ключ сессии')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = "cart"
        verbose_name = 'Корзины'
        verbose_name_plural = 'Корзина'
        ordering = ['id', ]

    objects = CartQuerySet().as_manager()

    def __str__(self):
        if self.user:
            return f"Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}"

        return f"Анонимная корзина | Товар {self.product.name} | Количество {self.quantity}"

    def products_price(self):
        return round(self.product.get_discount_price() * self.quantity, 2)

my_site/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string

from .models import Cart
from goods.models import Product
from carts.utils import get_user_cart


# Create your views here.

def cart_add(request):
    product_id = request.POST.get('product_id')
    product = Product.objects.get(id=product_id)

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)
    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, product=product)
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, product=product, quantity=1)

    # return redirect(request.META.get('HTTP_REFERER'))
    user_cart = get_user_cart(request)
    cart_items_html = render_to_string(
        "carts/includes/includedcart.html",
        context={
            "carts": user_cart
        },
        request=request
    )
    response_data = {
        "message": "Товар добавлен в корзину",
        "cart_items_html": cart_items_html
    }
    return JsonResponse(response_data)

def cart_change(request):
    cart_id = request.POST.get('cart_id')
    quantity = request.POST.get('quantity')

    cart = Cart.objects.get(id=cart_id)
    cart.quantity = quantity
    cart.save()

    cart = get_user_cart(request)

    cart_items_html = render_to_string(
        "carts/includes/includedcart.html",
        context={
            "carts": cart
        },
        request=request
    )
    # return redirect(request.META.get('HTTP_REFERER'))
    response_data = {
        "message": "Количество изменено",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }
    return JsonResponse(response_data)


def cart_remove(request):
    cart_id = request.POST.get('cart_id')
    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_cart(request)
    cart_items_html = render_to_string(
        "carts/includes/includedcart.html",
        context={
            "carts": user_cart
        },
        request=request
    )
    # return redirect(request.META.get('HTTP_REFERER'))
    response_data = {
        "message": "Товар удален",
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }
    return JsonResponse(response_data)

my_site/carts/templates/carts/includes/includedcart.html
{% load static %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">{{ cart.product.name }}</h5>
        </div>
        <li class="list-group-item">
            <div class="row text-center">
                <div class="col p-0">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}"
                                    data-cart-change-url="{% url 'cart:cart_change' %}">
                                {% csrf_token %}
                                -</button>
                        </span>
                        <input type="text" class="form-control number" value="{{ cart.quantity }}"
                               readonly>
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}"
                                    data-cart-change-url="{% url 'cart:cart_change' %}">
                                {% csrf_token %}
                                +</button>
                        </span>
                    </div>
                </div>
                <div class="col p-0">
                    <p>x {{ cart.product.get_discount_price }} = </p>
                </div>
                <div class="col p-0"><strong>{{ cart.products_price }} $</strong></div>
                <div class="col p-0">
                    <a href="{% url "cart:cart_remove" %}" class="remove-from-cart"
                       data-cart-id="{{ cart.id }}">
                        {% csrf_token %}
                        <img class="mx-1" src=
                                {% static "deps/icons/trash3-fill.svg" %} alt="Catalog Icon" width="16" height="16">
                    </a>
                </div>
            </div>
        </li>
        <ul class="list-group list-group-flush">
        </ul>
    {% endfor %}

</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_quantity }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price }} $</strong></h4>
    </div>
</div>
{% if carts and not order %}
    <a class="btn btn-dark" href="{% url "order:create_order" %}">
        Оформить заказ
    </a>
{% endif %}